# Hugo variables
#
baseurl = "/"
languageCode = "en-us"
title = "armchairtech"
# theme = "retrofulhugo"
theme = "hyde-hyde"
# theme = "hyde"
# theme = "after-dark"
# theme = "strange-case"
# theme = "casper-two"
# theme = "hugo-flex"
# theme = "base16"
# theme = "casper"

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 6
# optionally override the site's footer with custom copyright text
# copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
copyright = ""



[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
   tag = "tags"
   category = "categories"

[permalinks]
  posts = "/posts/:slug/"
  page = "/:slug/"

## Site Settings
[params]
    author = "John Hogenmiller"
    title = "YourTech"
    # description = "Just your average, ordinary, everyday, super admin."
    subtitle =  "Just your average, ordinary, everyday, super admin."
    authorimage = "/img/ytjohnthumbnail.png"
    logo = "img/ytjohnthumbnail.png"
    copyright = "Â© 2019 John Hogenmiller"
    dateformat = "2006-01-02"
    sourceurl = "https://gitlab.com/ytjohn/yourtech-us/tree/master/content" 
    highlightjs = true
    # highlightjsstyle = "github"
    highlightjsstyle = "tomorrow-night-bright"

    # themeColor = "theme-base-0b"
    # themeColor = "theme-base-yt01"
    # layoutReverse = true

    # author = "EM"
    authorAvatar = "/img/ytjohnthumbnail.png"
    authorLocation = "Western, PA"
    authorWebsite = "https://armchair.tech"
    authorDescription = "Just your average, ordinary, everyday, super admin."
    
    orgWebsite = "https://www.telematika.org"
    orgDescription = "Here is a description placeholder for your org"

    singleViewStyle = "casper"

## Social Accounts
[params.social]
    keybase = "ytjohn"
    github = "ytjohn"
    gitlab = "ytjohn"
    twitter = "thearmchairtech"
    stackoverflow = "ytjohn"
    email = "john@yourtech.us"


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
    name = "All Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
  name = "armchair.dev"
  url = "https://www.armchair.dev"
  weight = 200
