# Hugo variables
#
baseurl = "https://www.armchair.tech/"
baseURL = "https://www.armchair.tech/"


languageCode = "en"
defaultContentLanguage = "en"


title = "armchair.tech"
theme = "flatarm"

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 6
# optionally override the site's footer with custom copyright text
# copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
copyright = ""


[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
   tag = "tags"
   category = "categories"

[permalinks]
  page = "/:slug/"

## Site Settings
[params]
    author = "John Hogenmiller"
    title = "Armchair Technician"
    subtitle =  "Just your average, ordinary, everyday, super admin."
    avatar = "/img/ytjohnthumbnail.png"
    copyright = "John Hogenmiller"
    dateformat = "2006-01-02"
    sourceurl = "https://gitlab.com/ytjohn/armchairdottech/tree/master/content" 
    highlightjs = true
    highlightjsstyle = "tomorrow-night-bright"
    socialShare = true

    # themeColor = "theme-base-0b"
    # themeColor = "theme-base-yt01"
    # layoutReverse = true

    # author = "EM"
    authorAvatar = "/img/ytjohnthumbnail.png"
    authorLocation = "Western, PA"
    authorWebsite = "https://armchair.tech"
    authorDescription = "Just your average, ordinary, everyday, super admin."
    
    orgWebsite = "https://armchair.tech"
    orgDescription = "Just your average, ordinary, everyday, super admin."

    # singleViewStyle = "casper"
  [params.image]
    url = "img/ytjohnthumbnail.png"
    width = 800
    height = 600
  [params.logo]
    url = "img/ytjohnthumbnail.png"
    width = 127
    height = 40
  
## Social Accounts
[params.social]
    keybase = "ytjohn"
    github = "ytjohn"
    gitlab = "ytjohn"
    twitter = "thearmchairtech"
    stackoverflow = "ytjohn"
    email = "john@yourtech.us"

[params.share]
  Twitter = true
  Facebook = true
  #Reddit = true
  Linkedin = true

